#name: Checkout - Continuous Integration
#on:
#  pull_request:
#    branches:
#      - main
#      - ci
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#        with:
#          fetch-depth: 0
#      - name: Setup Java JDK
#        uses: actions/setup-java@v5.0.0
#        with:
#          java-version: '21'
#          distribution: 'jetbrains'
#      - name: Run compilation test
#        run: javac $(find . -name "*.java")